# Performance measurements of ML algorithms (Supervised)

In [6]:
#import library packages
import pandas as p
import numpy as n

In [7]:
import warnings
warnings.filterwarnings("ignore")

In [8]:
#Load given dataset
data = p.read_csv('Data.csv')
df=data.dropna()

In [11]:
df.columns

Index(['Unnamed: 0', 'ï»¿State_Name', 'Crop_Year', 'Area', 'Yield',
       'Temperature', 'Precipitaion', 'Humidity', 'Soil_type_chalky',
       'Soil_type_clay', 'Soil_type_loamy', 'Soil_type_peaty',
       'Soil_type_sandy', 'Soil_type_silt', 'Soil_type_silty',
       'District_AHMEDNAGAR', 'District_AKOLA', 'District_AMRAVATI',
       'District_AURANGABAD', 'District_BEED', 'District_BHANDARA',
       'District_BULDHANA', 'District_CHANDRAPUR', 'District_DHULE',
       'District_GADCHIROLI', 'District_GONDIA', 'District_HINGOLI',
       'District_JALGAON', 'District_JALNA', 'District_KOLHAPUR',
       'District_LATUR', 'District_NAGPUR', 'District_NANDED',
       'District_NANDURBAR', 'District_NASHIK', 'District_OSMANABAD',
       'District_PARBHANI', 'District_PUNE', 'District_SANGLI',
       'District_SATARA', 'District_SOLAPUR', 'District_THANE',
       'District_WARDHA', 'District_WASHIM', 'District_YAVATMAL', 'Crop_Bajra',
       'Crop_Jowar', 'Crop_Wheat', 'Season_Kharif', 'Season_Rabi',
       'Season_Rabi.1'],
      dtype='object')

In [12]:
del df['Unnamed: 0']

In [13]:
df

,ï»¿State_Name,Crop_Year,Area,Yield,Temperature,Precipitaion,Humidity,Soil_type_chalky,Soil_type_clay,Soil_type_loamy,...,District_THANE,District_WARDHA,District_WASHIM,District_YAVATMAL,Crop_Bajra,Crop_Jowar,Crop_Wheat,Season_Kharif,Season_Rabi,Season_Rabi.1
0,0,0,779,217000,226,452,63,0,1,0,...,0,0,0,0,0,1,0,0,1,0
1,0,1,758,227900,38,107,49,0,0,0,...,0,0,0,0,0,1,0,0,1,0
2,0,2,768,190900,16,424,14,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3,0,3,772,160800,51,113,12,0,1,0,...,0,0,0,0,0,1,0,0,1,0
4,0,4,775,175000,77,25,8,0,1,0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,0,13,399,61400,285,311,24,0,0,1,...,0,0,0,1,0,0,1,0,0,1
1341,0,14,344,58500,309,277,22,0,0,1,...,0,0,0,1,0,0,1,0,0,1
1342,0,15,359,64600,330,277,45,0,0,0,...,0,0,0,1,0,0,1,0,0,1
1343,0,16,348,30700,336,18,3,0,0,1,...,0,0,0,1,0,0,1,0,0,1
1344,0,17,304,26800,297,219,16,0,0,1,...,0,0,0,1,0,0,1,0,0,1

In [14]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['ï»¿State_Name', 'Crop_Year', 'Area', 'Yield',
       'Temperature', 'Precipitaion', 'Humidity', 'Soil_type_chalky',
       'Soil_type_clay', 'Soil_type_loamy', 'Soil_type_peaty',
       'Soil_type_sandy', 'Soil_type_silt', 'Soil_type_silty',
       'District_AHMEDNAGAR', 'District_AKOLA', 'District_AMRAVATI',
       'District_AURANGABAD', 'District_BEED', 'District_BHANDARA',
       'District_BULDHANA', 'District_CHANDRAPUR', 'District_DHULE',
       'District_GADCHIROLI', 'District_GONDIA', 'District_HINGOLI',
       'District_JALGAON', 'District_JALNA', 'District_KOLHAPUR',
       'District_LATUR', 'District_NAGPUR', 'District_NANDED',
       'District_NANDURBAR', 'District_NASHIK', 'District_OSMANABAD',
       'District_PARBHANI', 'District_PUNE', 'District_SANGLI',
       'District_SATARA', 'District_SOLAPUR', 'District_THANE',
       'District_WARDHA', 'District_WASHIM', 'District_YAVATMAL', 'Crop_Bajra',
       'Crop_Jowar', 'Crop_Wheat', 'Season_Kharif', 'Season_Rabi',
       'Season_Rabi.1']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [15]:
#According to the cross-validated MCC scores, the random forest is the best-performing model, so now let's evaluate its performance on the test set.
from sklearn.metrics import confusion_matrix, classification_report, matthews_corrcoef, cohen_kappa_score, accuracy_score, average_precision_score, roc_auc_score

In [16]:
X = df.drop(labels='Yield', axis=1)
#Response variable
y = df.loc[:,'Yield']

In [17]:
#We'll use a test size of 30%. We also stratify the split on the response variable, which is very important to do because there are so few fraudulent transactions.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [20]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()

dt.fit(X_train,y_train)

predictR = dt.predict(X_test)

print("")

# variance score: 1 means perfect prediction
print('Variance score: {}'.format(dt.score(X_test, y_test)))

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("")
mbe=mean_absolute_error(y_test,predictR)
print('mean_absolute_error : ',mbe)
print("")
mse=mean_squared_error(y_test,predictR)
print('mean_squared_error : ',mse)

print("")
r2=r2_score(y_test,predictR)
print('R_squared_ : ',r2)

Variance score: 0.870599999676776

mean_absolute_error :  54.43090638930163

mean_squared_error :  7350.115898959881

R_squared_ :  0.870599999676776

In [21]:
from sklearn.linear_model import ElasticNet
el = ElasticNet()


el.fit(X_train,y_train)

predictR = el.predict(X_test)
print("")

# regression coefficients
# print('Coefficients: ', regr.oob_score_)
 
# variance score: 1 means perfect prediction
print('Variance score: {}'.format(el.score(X_test, y_test)))

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print("")
mbe=mean_absolute_error(y_test,predictR)
print('mean_absolute_error : ',mbe)
print("")
mse=mean_squared_error(y_test,predictR)
print('mean_squared_error : ',mse)

print("")
r2=r2_score(y_test,predictR)
print('R_squared_ : ',r2)

Variance score: 0.9039331312279286

mean_absolute_error :  51.39509041059759

mean_squared_error :  5456.7435684787015

R_squared_ :  0.9039331312279286